version: '3.8'

services:
  web:
    build: .
    image: heart-api:latest   # <= forces a valid image name
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
